version: "3"

services:
  dbpostgres:
    image: postgres:12.12
    container_name: dbpostgres
    environment:
      - POSTGRES_USER=ldav12ea
      - POSTGRES_PASSWORD=21321dsad12gfq12rfvaADA
      - POSTGRES_DB=xakaton
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5454:5432
  classificator_by_category:
    image: classificator
    container_name: classificator_by_category
    volumes:
      - ./nlp_model/model_classification.txt:/opt/project/xakaton/data/model.txt
    ports:
      - 9994:9994
  classificator_by_priority:
    image: classificator
    container_name: classificator_by_priority
    volumes:
      - ./nlp_model/model_priority.txt:/opt/project/xakaton/data/model.txt
    ports:
      - 9995:9994
  javaui:
    image: javaui
    container_name: javaui
    environment:
      db_username:
      db_password:
      db_url:
    ports:
      - 8083:8083
volumes:
    db:

